# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-pandas-utils',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-pandas-utils',
                'lib_path': 'cjm_pandas_utils'},
  'syms': { 'cjm_pandas_utils.core': { 'cjm_pandas_utils.core.markdown_to_pandas': ( 'core.html#markdown_to_pandas',
                                                                                     'cjm_pandas_utils/core.py')}}}
